apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque

stringData:
  POSTGRES_PASSWORD: "zde_bude_skutecne_heslo_vlozeno_pri_nasazeni"
  DATABASE_URL: "postgresql://postgres:zde_bude_skutecne_heslo_vlozeno_pri_nasazeni@postgres-service:5432/events_db?schema=public"